# Docker Compose for Test Environment
# Spins up all services needed for testing

version: '3.8'

services:
  # PostgreSQL Test Database
  postgres-test:
    image: postgres:15-alpine
    container_name: reedi-test-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reedi_test
    ports:
      - "5433:5432"  # Use 5433 to avoid conflict with dev DB
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # LocalStack (AWS S3 emulation)
  localstack:
    image: localstack/localstack:latest
    container_name: reedi-test-s3
    environment:
      SERVICES: s3
      DEBUG: 0
      DATA_DIR: /tmp/localstack/data
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1
    ports:
      - "4566:4566"  # LocalStack gateway
      - "4571:4571"  # LocalStack S3
    volumes:
      - localstack-data:/tmp/localstack
      - ./localstack-init.sh:/docker-entrypoint-initaws.d/init.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Redis (for caching and sessions in tests)
  redis-test:
    image: redis:7-alpine
    container_name: reedi-test-redis
    ports:
      - "6380:6379"  # Use 6380 to avoid conflict with dev Redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # RabbitMQ (for media processing queue in tests - optional)
  rabbitmq-test:
    image: rabbitmq:3-management-alpine
    container_name: reedi-test-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: test
      RABBITMQ_DEFAULT_PASS: test
    ports:
      - "5673:5672"   # AMQP port (use 5673 to avoid conflict)
      - "15673:15672" # Management UI (use 15673 to avoid conflict)
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-test-data:
  localstack-data:

